/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MonthlySummaryService } from "../monthlySummary.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MonthlySummaryCreateInput } from "./MonthlySummaryCreateInput";
import { MonthlySummary } from "./MonthlySummary";
import { MonthlySummaryFindManyArgs } from "./MonthlySummaryFindManyArgs";
import { MonthlySummaryWhereUniqueInput } from "./MonthlySummaryWhereUniqueInput";
import { MonthlySummaryUpdateInput } from "./MonthlySummaryUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MonthlySummaryControllerBase {
  constructor(
    protected readonly service: MonthlySummaryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MonthlySummary })
  @nestAccessControl.UseRoles({
    resource: "MonthlySummary",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMonthlySummary(
    @common.Body() data: MonthlySummaryCreateInput
  ): Promise<MonthlySummary> {
    return await this.service.createMonthlySummary({
      data: {
        ...data,

        hostel: {
          connect: data.hostel,
        },
      },
      select: {
        chefFee: true,
        createdAt: true,

        hostel: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [MonthlySummary] })
  @ApiNestedQuery(MonthlySummaryFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "MonthlySummary",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async monthlySummaries(
    @common.Req() request: Request
  ): Promise<MonthlySummary[]> {
    const args = plainToClass(MonthlySummaryFindManyArgs, request.query);
    return this.service.monthlySummaries({
      ...args,
      select: {
        chefFee: true,
        createdAt: true,

        hostel: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MonthlySummary })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MonthlySummary",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async monthlySummary(
    @common.Param() params: MonthlySummaryWhereUniqueInput
  ): Promise<MonthlySummary | null> {
    const result = await this.service.monthlySummary({
      where: params,
      select: {
        chefFee: true,
        createdAt: true,

        hostel: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MonthlySummary })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MonthlySummary",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMonthlySummary(
    @common.Param() params: MonthlySummaryWhereUniqueInput,
    @common.Body() data: MonthlySummaryUpdateInput
  ): Promise<MonthlySummary | null> {
    try {
      return await this.service.updateMonthlySummary({
        where: params,
        data: {
          ...data,

          hostel: {
            connect: data.hostel,
          },
        },
        select: {
          chefFee: true,
          createdAt: true,

          hostel: {
            select: {
              id: true,
            },
          },

          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MonthlySummary })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MonthlySummary",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMonthlySummary(
    @common.Param() params: MonthlySummaryWhereUniqueInput
  ): Promise<MonthlySummary | null> {
    try {
      return await this.service.deleteMonthlySummary({
        where: params,
        select: {
          chefFee: true,
          createdAt: true,

          hostel: {
            select: {
              id: true,
            },
          },

          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
